---

# This file is part of the k8s-gluster-heketi-ansible project,
# an ansible collection to install glusterfs and heketi into
# kubernetes to provide dynamic persistent volumes.
#
# (c) 2020 Andreas Florath, Deutsche Telekom AG
#
# By default all files of this project are licensed under the Apache-2.0
# license. For details see the file 'LICENSE' in the top directory.
# https://opensource.org/licenses/Apache-2.0
#
# SPDX-License-Identifier: Apache-2.0

# Common thingies for the heketi installation

- name: "Create local dir for file detemplation"
  file:
    state: directory
    path: detemplized
    mode: '0755'

- name: "Create heketi.json file locally"
  template:
    src: heketi.json
    dest: detemplized/heketi.json

- name: "Encode heketi.json"
  set_fact:
    heketi_json_base64: "{{ item | string | b64encode }}"
  with_file:
    - detemplized/heketi.json
  no_log: True

- name: "Create topology file"
  template:
    src: heketi-topology.json
    dest: detemplized/heketi-topology.json
  delegate_to: localhost

- name: "Encode heketi-topology.json"
  set_fact:
    topology_json_base64: "{{ item | string | b64encode }}"
  with_file:
    - detemplized/heketi-topology.json
  no_log: True

- name: "Encode ssh key"
  set_fact:
    private_key_base64: "{{ item | string | b64encode }}"
  with_file:
    - "{{ gluster_host_ssh_priv_key }}"
  no_log: True
