---

# This file is part of the k8s-gluster-heketi-ansible project,
# an ansible collection to install glusterfs and heketi into
# kubernetes to provide dynamic persistent volumes.
#
# (c) 2020 Andreas Florath, Deutsche Telekom AG
#
# By default all files of this project are licensed under the Apache-2.0
# license. For details see the file 'LICENSE' in the top directory.
# https://opensource.org/licenses/Apache-2.0
#
# SPDX-License-Identifier: Apache-2.0

kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-heketi
  labels:
    glusterfs: heketi-deployment
    deploy-heketi: deployment
  annotations:
    description: Defines how to deploy Heketi
  namespace: "{{ heketi_namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deploy-heketi
  template:
    metadata:
      name: deploy-heketi
      labels:
        name: deploy-heketi
        glusterfs: heketi-pod
        deploy-heketi: pod
    spec:
      serviceAccountName: heketi-service-account
      containers:
      - image: "{{ heketi_image }}"
        imagePullPolicy: IfNotPresent
        name: deploy-heketi
        env:
          - name: HEKETI_USER_KEY
            value: "{{ heketi_user_key }}"
          - name: HEKETI_ADMIN_KEY
            value: "{{ heketi_admin_key }}"
          - name: HEKETI_EXECUTOR
            value: "kubernetes"
          - name: HEKETI_KUBE_NAMESPACE
            value: "{{ heketi_namespace }}"
          - name: HEKETI_FSTAB
            value: "/var/lib/heketi/fstab"
          - name: HEKETI_SNAPSHOT_LIMIT
            value: '14'
          - name: HEKETI_KUBE_GLUSTER_DAEMONSET
            value: "y"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: db
          mountPath: "/var/lib/heketi"
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: "/hello"
            port: 8080
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 30
          httpGet:
            path: "/hello"
            port: 8080
      volumes:
      - name: db
